version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "org.junit.jupiter:junit-jupiter"
        versions: [ ">=6.0.0" ]
