name: Gradle Build

on: [push, pull_request]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - name: Gradlew build
      env:
        MONGO_ADDRESS: "localhost:27017"
      run: ./gradlew build
